# Node.js with gulp
# Build a Node.js project using the gulp task runner.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- task: Npm@1
  displayName: npm install
  inputs:
    verbose: true
- task: Npm@1
  displayName: npm run build
  inputs:
    command: custom
    verbose: true
    customCommand: run build
- task: ArchiveFiles@2
  displayName: Archive files
  inputs:
    rootFolderOrFile: $(System.DefaultWorkingDirectory)
    includeRootFolder: false
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts: drop'
  inputs:
    TargetPath: '\\my\share\$(Build.DefinitionName)\$(Build.BuildNumber)'
